from dataclasses import dataclass

from danmukuflow.core import Canvas, MoveEffect, format_ass_time
from danmukuflow.models import RenderConfig


@dataclass(frozen=True)
class AssRenderResult:
    content: str
    parsed_count: int
    rendered_count: int
    skipped_count: int


def render_ass(danmakus, title, config=None):
    return render_ass_document(danmakus, title, config).content


def render_ass_document(danmakus, title, config=None):
    config = config or RenderConfig()
    ordered = sorted(danmakus, key=lambda item: item.timeline_s)
    canvas = Canvas(config)
    dialogues = []
    skipped_count = 0

    for danmaku in ordered:
        if any(term in danmaku.content for term in config.denylist):
            skipped_count += 1
            continue
        drawable = canvas.draw(danmaku)
        if drawable is None:
            skipped_count += 1
            continue
        dialogues.append(_format_dialogue(drawable))

    return AssRenderResult(
        content=_format_document(title, config, dialogues),
        parsed_count=len(ordered),
        rendered_count=len(dialogues),
        skipped_count=skipped_count,
    )


def escape_text(text):
    text = text.strip()
    if "\n" in text:
        return text.replace("\n", "\\N")
    return text


def _format_document(title, config, dialogues):
    lines = [
        "[Script Info]",
        "; Script generated by DanmukuFlow",
        "Title: {}".format(title),
        "Script Updated By: DanmukuFlow (https://github.com/AsyncKurisu/DanmukuFlow)",
        "ScriptType: v4.00+",
        "PlayResX: {}".format(config.width),
        "PlayResY: {}".format(config.height),
        "Aspect Ratio: {}:{}".format(config.width, config.height),
        "Collisions: Normal",
        "WrapStyle: 2",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.601",
        "",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    ]
    lines.extend(_format_styles(config))
    lines.extend(
        [
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ]
    )
    lines.extend(dialogues)
    return "\n".join(lines) + "\n"


def _format_styles(config):
    return [
        _format_style("Float", config),
        _format_style("Bottom", config),
        _format_style("Top", config),
    ]


def _format_style(name, config):
    opacity = config.opacity
    return (
        "Style: {name},{font},{font_size},&H{opacity:02x}FFFFFF,&H00FFFFFF,"
        "&H{opacity:02x}000000,&H00000000,{bold}, 0, 0, 0, 100, 100, "
        "0.00, 0.00, 1, {outline}, 0, 7, 0, 0, 0, 1"
    ).format(
        name=name,
        font=config.font,
        font_size=config.font_size,
        opacity=opacity,
        bold=config.bold_value,
        outline=config.outline,
    )


def _format_dialogue(drawable):
    danmaku = drawable.danmaku
    start = format_ass_time(danmaku.timeline_s)
    end = format_ass_time(danmaku.timeline_s + drawable.duration)
    r, g, b = danmaku.rgb
    return (
        "Dialogue: 2,{start},{end},{style},,0,0,0,,"
        "{{{effect}\\c&H{b:02x}{g:02x}{r:02x}&}}{text}"
    ).format(
        start=start,
        end=end,
        style=drawable.style_name,
        effect=_format_effect(drawable.effect),
        b=b,
        g=g,
        r=r,
        text=escape_text(danmaku.content),
    )


def _format_effect(effect):
    if isinstance(effect, MoveEffect):
        x0, y0 = effect.start
        x1, y1 = effect.end
        return "\\move({}, {}, {}, {})".format(x0, y0, x1, y1)
    raise TypeError("unsupported ASS effect")
